collector:
  image: cilium/docker-collector
  command: -f '.*docker-collector.*'
  container_name: docker-collector
  pid: "host"
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - HOSTNAME
    - ELASTIC_IP=elastic
    - ELASTIC_PORT=9200
  links:
    - elastic

elastic:
  image: elasticsearch:1.7.1
  command: elasticsearch
  container_name: docker-collector-elastic
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: kibana:4.1.1
  container_name: docker-collector-kibana
  environment:
    - ELASTICSEARCH_URL=http://elastic:9200
  ports:
    - 5601:5601
  links:
    - elastic
